name: 's3-multibranch-deploy-preview'

description: 'Deploy preview of your frontend to S3 bucket for each branch in repository'

inputs:
  aws_region:
    description: 'AWS region of the S3 bucket'
    default: 'us-east-1'
    required: true
  aws_assume_role:
    description: 'ARN of the role to be assumed'
    default: ''
    required: true
  aws_bucket:
    description: 'Name of the S3 bucket'
    default: ''
    required: true
  folder:
    description: 'Folder to be deployed in S3 bucket'
    default: './site'
    required: true
  max_branch_deployed:
    description: 'Maximum number of branches to be deployed'
    default: '50'
    required: false
  max_commit_per_branch_deployed:
    description: 'Maximum number of commit per branch to be deployed'
    default: '10'
    required: false

outputs:
  preview_url:
    description: 'URL of the deployed preview'

runs:
  using: composite
  steps:
  - name: Download source
    uses: actions/checkout@v3
  - name: configure AWS credentials
    id: creds
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: ${{ inputs.aws_assume_role }}
      role-session-name: samplerolesession
      aws-region: ${{ inputs.aws_region }}
  - name: Deploy preview
    id: deploy
    shell: bash
    run: |
        echo "::group::Deploying preview to AWS S3"
        bash entrypoint.sh
        echo "::endgroup::"